-- SQLite + sqlite-vec schema generated by rager export --sqlite
CREATE TABLE IF NOT EXISTS rag_chunks (
  rowid INTEGER PRIMARY KEY,
  chunk_id TEXT NOT NULL UNIQUE,
  text TEXT NOT NULL,
  metadata_json TEXT,
  source TEXT,
  path TEXT,
  url TEXT
);

-- Requires sqlite-vec extension:
-- https://github.com/asg017/sqlite-vec
CREATE VIRTUAL TABLE IF NOT EXISTS rag_vec USING vec0(
  embedding float[1536]
);

CREATE INDEX IF NOT EXISTS rag_chunks_chunk_id_idx ON rag_chunks(chunk_id);
