#!/usr/bin/env node
/**
 * Generates a new skill directory with SKILL.md configured for RAG URL or embedded rag.json.
 */
import {
  mkdirSync,
  writeFileSync,
  existsSync,
  statSync
} from 'node:fs';
import path from 'node:path';

function parseArgs(argv) {
  const out = {
    name: null,
    description: null,
    rag: 'embedded',
    ragUrl: '',
    ragPath: './public/rag.json',
    out: null,
    help: false
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const next = () => argv[++i];
    if (a === '-h' || a === '--help') out.help = true;
    else if (a === '--name') out.name = next();
    else if (a === '--description') out.description = next();
    else if (a === '--rag') out.rag = next();
    else if (a === '--rag-url') out.ragUrl = next();
    else if (a === '--rag-path') out.ragPath = next();
    else if (a === '--out') out.out = next();
  }
  return out;
}

function printHelp() {
  console.log(`generate-skill — scaffold SKILL.md with RAG (url | embedded)

Usage:
  node scripts/generate-skill.mjs --name <skill-name> --rag <url|embedded> [options] --out <dir>

Options:
  --name           Skill id (lowercase, hyphens, max 64 chars)
  --description    Optional; default generated from name + RAG mode
  --rag            url | embedded (default: embedded)
  --rag-url        Required when --rag url — HTTPS or HTTP URL to rag.json
  --rag-path       For embedded mode — path to rag.json (default: ./public/rag.json)
  --out            Output directory (created)

Examples:
  node scripts/generate-skill.mjs --name acme-docs --rag url --rag-url https://cdn.example/rag.json --out ./.cursor/skills/acme-docs
  node scripts/generate-skill.mjs --name acme-docs --rag embedded --rag-path ./public/rag.json --out ./skills/acme-docs
`);
}

function validateName(name) {
  if (!name || !/^[a-z0-9][a-z0-9-]{0,62}$/.test(name)) {
    console.error(
      'Invalid --name: use lowercase letters, numbers, hyphens only; max 64 chars.'
    );
    process.exit(1);
  }
}

function buildBodyUrl({ name, ragUrl, description }) {
  return `# ${name}

## RAG (remote URL)

- **Index URL (\`RAG_JSON_URL\`)**: \`${ragUrl}\`
- **Format**: JSON with a top-level \`chunks\` array (or array root); each chunk has at least \`text\`; optional \`embedding\`, \`metadata\`, \`id\`.

### Retrieval workflow

1. \`fetch(RAG_JSON_URL)\` → parse JSON.
2. Normalize chunks to a list of { id, text, embedding?, metadata? }.
3. For the user query, rank chunks (embeddings + cosine similarity if available; else keyword overlap).
4. Answer using only supported chunk content; cite chunk id or \`metadata.source\` when present.

## Domain instructions

(Add task-specific steps, conventions, and output formats below.)

---

_Generated by skill-generator-rag (URL mode). Skill: **${name}**._
_Description: ${description}_
`;
}

function buildBodyEmbedded({ name, ragPath, description }) {
  return `# ${name}

## RAG (embedded standalone)

- **Index path (\`RAG_EMBEDDED_PATH\`)**: \`${ragPath}\` (relative to repository root unless absolute).
- **Format**: Same as URL mode: JSON with chunked text and optional embeddings.

### Retrieval workflow

1. Read the file at \`RAG_EMBEDDED_PATH\` (from workspace root).
2. Parse JSON; normalize chunks as for URL mode.
3. Rank and retrieve for the user query; answer with citations when possible.

### No network

This mode does not require \`fetch\`; the index ships with the project (standalone RAG).

## Domain instructions

(Add task-specific steps below.)

---

_Generated by skill-generator-rag (embedded mode). Skill: **${name}**._
_Description: ${description}_
`;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help || !args.out) {
    printHelp();
    process.exit(args.help ? 0 : 1);
  }
  if (!args.name) {
    console.error('Missing --name');
    printHelp();
    process.exit(1);
  }
  validateName(args.name);
  const mode = String(args.rag).toLowerCase();
  if (mode !== 'url' && mode !== 'embedded') {
    console.error('--rag must be "url" or "embedded"');
    process.exit(1);
  }
  if (mode === 'url' && !args.ragUrl) {
    console.error('--rag url requires --rag-url');
    process.exit(1);
  }

  const defaultDesc =
    args.description ||
    (mode === 'url'
      ? `Uses remote RAG at a JSON URL for grounded answers. Use when working with ${args.name.replace(/-/g, ' ')} or when retrieval from the configured index is needed.`
      : `Uses embedded rag.json at ${args.ragPath} for grounded answers. Use when working with ${args.name.replace(/-/g, ' ')} or offline RAG retrieval.`);

  const yamlDesc = defaultDesc.replace(/\n/g, ' ').trim();
  const frontmatter = `---
name: ${args.name}
description: >-
  ${yamlDesc}
---

`;

  const body =
    mode === 'url'
      ? buildBodyUrl({
          name: args.name,
          ragUrl: args.ragUrl,
          description: defaultDesc
        })
      : buildBodyEmbedded({
          name: args.name,
          ragPath: args.ragPath,
          description: defaultDesc
        });

  const outDir = path.resolve(args.out);
  if (existsSync(outDir) && !isDir(outDir)) {
    console.error(`Output exists and is not a directory: ${outDir}`);
    process.exit(1);
  }
  mkdirSync(outDir, { recursive: true });
  const skillPath = path.join(outDir, 'SKILL.md');
  writeFileSync(skillPath, frontmatter + body, 'utf8');
  console.log(`Wrote ${skillPath}`);
}

function isDir(p) {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}

main();
